
# simulation parameters
###
# .. code-block:: yaml
#
#    - dt: time step size
#    - operating_mode: specifies operating mode: either single_scenario, single_vehicle, evaluation, or benchmark
#    - ego_vehicle_id: ego vehicle ID
#    - scenario_directories: directories in which CommonRoad scenarios are located
#    - num_vehicles: number of vehicles which should be evaluated
#    - benchmark_id: CommonRoad solution file name
#    - evaluation_dirs: list of directories which contain scenarios which should be evaluated
#    - rule_set: set of traffic rules which should be evaluated (see traffic_rules.yaml)
#    - verbose_mode: activate/deactivate status output of algorithms and simulation
#    - time_measuring: activate/deactivate computation time measuring
simulation_param:
  dt: 0.2
  evaluation_mode: test # single_scenario, single_vehicle, test, statistic
  ego_vehicle_id: 1008
  scenario_dir: /../scenarios/test_interstate/
  benchmark_id: DEU_test_safe_distance
  scenario_directories:  ["/scenarios/test_interstate"]
  verbose_mode: false
  time_measuring: false
  operating_mode: monitor # one of monitor, constraint, robustness


# road network and curvilinear coordinate system parameters
###
# .. code-block:: yaml
#
#    - num_chankins_corner_cutting: number of how often chankins algorithm should be applied
#    - polyline_resampling_step: step size for polyline resampling
#    - merging_length: maximum accumulated length of lanalets belonging to a lane
road_network_param:
  num_chankins_corner_cutting: 1
  polyline_resampling_step: 0.5
  merging_length: 10000

# Ego vehicle parameters
###
# .. code-block:: yaml
#
#    - vehicle_number: CommonRoad vehicle number; possible options are 1, 2 or 3 (see CommonRoad vehicle models)
#    - a_max: maximum acceleration of egovehicle
#    - a_min: minimum acceleration of egovehicle
#    - j_max: maximum jerk of ego vehicle
#    - j_min: minimum jerk of ego vehicle
#    - v_des: desired velocity of ego vehicle
#    - t_react: reaction time of ego vehicle
#    - dynamics_param: physical parameters of ego vehicle; will be initialized during runtime
#    - fov: field of view (sensor range)
#    - v_min: minimum allowed velocity considering vehicle dynamics
#    - const_dist_offset: minimum distance at standstill
#    - emergency_profile: emergency jerk profile
#    - emergency_profile_num_steps_fb: number of steps minimum jerk should be attended to emergency profile
#    - fov_speed_limit: speed limit based on field of view
#    - braking_speed_limit: speed limit to ensure comfortable braking within field of view
#    - road_condition_speed_limit: speed limit based on road conditions

ego_vehicle_param:
  vehicle_number: 2
  a_max: 3
  a_min: -10.0
  a_corr: 0.0
  j_max: 10
  j_min: -10
  v_des: 30
  t_react: 0.4
  dynamics_param: None
  fov: 200
  v_min: 0
  const_dist_offset: 0
  emergency_profile: []
  emergency_profile_num_steps_fb: 200
  fov_speed_limit: 50 # compute with calc_v_max_fov(ego_vehicle_param, simulation_param)
  braking_speed_limit: 43 # compute with calc_v_max_braking(ego_vehicle_param, simulation_param, traffic_rule_param)
  road_condition_speed_limit: 50

# Other vehicle's parameters
###
# .. code-block:: yaml
#
#    - vehicle_number: CommonRoad vehicle number; possible options are 1, 2 or 3 (see CommonRoad vehicle models)
#    - v_max: maximum velocity of leading vehicle
#    - v_min: minimum velocity of leading vehicle
#    - a_max: maximum acceleration of leading vehicle
#    - a_min: minimum acceleration of leading vehicle
#    - j_max: maximum jerk of leading vehicle
#    - j_min: minimum jerk of leading vehicle
#    - t_react: reaction time of ego vehicle

other_vehicles_param:
    vehicle_number: 2
    v_max: 60
    v_min: 0
    a_max: 5
    a_min: -10.5
    j_max: 10
    j_min: -10
    t_react: 0.4 # for safe distance calculation of preceding vehicles
    dynamics_param: None  # TODO replace dynamics parameter with worst case behavior

# Visualization parameters
###
#    - Parameters for plotting of profiles
#    - Parameters for video creation
visualization:
    # Parameters for plotting of profiles
    ###
    # .. code-block:: yaml
    #
    #   - width: width of matplotlib figure
    #   - line_width: line width of profiles
    #   - font_size: font size of text within the plot
    #   - axes_line_width: line width of the axes
    #   - figure_type: type of figure which should be stored
    plot:
        width: 3.75
        line_width: 0.75
        font_size: 9
        axes_line_width: 0.25
        figure_type: eps

    # Parameters for video creation
    ###
    # .. code-block:: yaml
    #
    #   - obstacle_label: activate/deactivate visualization of obstacle label (ID) in video
    video:
        obstacle_label : True